// Canon videos for live pages. Reads the always-available local video picks
// generated by scripts/canon-resolve.mjs (canon-videos.json). A live page asks
// for a slot (e.g. 'video-hero') and gets back a Hero-ready {desktop, mobile,
// poster}. Serving goes through videoUrl() exactly like a hardcoded path, so
// changing the pick on /admin/canon changes WHICH file plays, never how it is
// served. Empty or remote slots fall back, so a page never breaks.
import { videoUrl } from './media';
import data from './canon-videos.json';

export interface CanonVideoEntry {
  label: string;
  desktopFile: string;
  mobileFile: string;
  poster: string | null;
  consent: string;
  dataClass: string;
  status: string;
}

export interface VideoSrc {
  desktop: string;
  mobile: string;
  poster: string;
}

const videos = (data as { videos: Record<string, CanonVideoEntry> }).videos ?? {};

/** The resolved canon video for a slot, or null if it has no always-available local pick. */
export function canonVideo(slot: string): CanonVideoEntry | null {
  return videos[slot] ?? null;
}

/** Resolve a canon video slot to a {desktop, mobile, poster} source, or the fallback. */
export function canonVideoSrc(slot: string, fallback: VideoSrc): VideoSrc {
  const v = canonVideo(slot);
  if (!v) return fallback;
  return {
    desktop: videoUrl(v.desktopFile),
    mobile: videoUrl(v.mobileFile),
    poster: v.poster ?? fallback.poster,
  };
}
